// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * DevelopmentChatCreate
 */
export type DevelopmentChatCreate = {
    /**
     * Content
     */
    content: string;
};

/**
 * DevelopmentChatPublic
 */
export type DevelopmentChatPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Workspace Ready
     */
    workspace_ready: boolean;
    presence_mode: PresenceMode;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * DevelopmentChatUpdate
 */
export type DevelopmentChatUpdate = {
    /**
     * Title
     */
    title?: string | null;
    presence_mode?: PresenceMode | null;
};

/**
 * DevelopmentChatsPublic
 */
export type DevelopmentChatsPublic = {
    /**
     * Data
     */
    data: Array<DevelopmentChatPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * DevelopmentMessageCreate
 */
export type DevelopmentMessageCreate = {
    /**
     * Content
     */
    content: string;
};

/**
 * DevelopmentMessageKind
 */
export type DevelopmentMessageKind = 'message' | 'proposal';

/**
 * DevelopmentMessagePublic
 */
export type DevelopmentMessagePublic = {
    role: DevelopmentMessageRole;
    /**
     * Content
     */
    content: string;
    kind?: DevelopmentMessageKind;
    proposal_state?: DevelopmentProposalState | null;
    /**
     * Activity
     */
    activity?: Array<{
        [key: string]: string;
    }>;
    /**
     * Duration Seconds
     */
    duration_seconds?: number | null;
    /**
     * Id
     */
    id: string;
    /**
     * Chat Id
     */
    chat_id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * DevelopmentMessageRole
 */
export type DevelopmentMessageRole = 'user' | 'assistant';

/**
 * DevelopmentMessagesPublic
 */
export type DevelopmentMessagesPublic = {
    /**
     * Data
     */
    data: Array<DevelopmentMessagePublic>;
    /**
     * Has More
     */
    has_more: boolean;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * DevelopmentPresenceUpdate
 */
export type DevelopmentPresenceUpdate = {
    presence_mode: PresenceMode;
};

/**
 * DevelopmentProposalState
 */
export type DevelopmentProposalState = 'undecided' | 'approved' | 'rejected';

/**
 * DevelopmentWorkspacePublic
 */
export type DevelopmentWorkspacePublic = {
    /**
     * Ready
     */
    ready: boolean;
    /**
     * Setup Available
     */
    setup_available: boolean;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PresenceMode
 */
export type PresenceMode = 'stop_when_i_leave' | 'continue_in_background';

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Concurrent Agent Turn Limit
     */
    concurrent_agent_turn_limit?: number;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Concurrent Agent Turn Limit
     */
    concurrent_agent_turn_limit?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Concurrent Agent Turn Limit
     */
    concurrent_agent_turn_limit?: number | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersBulkDelete
 */
export type UsersBulkDelete = {
    /**
     * User Ids
     */
    user_ids: Array<string>;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersBulkDeleteUsersData = {
    body: UsersBulkDelete;
    path?: never;
    query?: never;
    url: '/api/v1/users/bulk-delete';
};

export type usersBulkDeleteUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersBulkDeleteUsersError = usersBulkDeleteUsersErrors[keyof usersBulkDeleteUsersErrors];

export type usersBulkDeleteUsersResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersBulkDeleteUsersResponse = usersBulkDeleteUsersResponses[keyof usersBulkDeleteUsersResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type itemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type itemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemsError = itemsReadItemsErrors[keyof itemsReadItemsErrors];

export type itemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type itemsReadItemsResponse = itemsReadItemsResponses[keyof itemsReadItemsResponses];

export type itemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type itemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsCreateItemError = itemsCreateItemErrors[keyof itemsCreateItemErrors];

export type itemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsCreateItemResponse = itemsCreateItemResponses[keyof itemsCreateItemResponses];

export type itemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsDeleteItemError = itemsDeleteItemErrors[keyof itemsDeleteItemErrors];

export type itemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type itemsDeleteItemResponse = itemsDeleteItemResponses[keyof itemsDeleteItemResponses];

export type itemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemError = itemsReadItemErrors[keyof itemsReadItemErrors];

export type itemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsReadItemResponse = itemsReadItemResponses[keyof itemsReadItemResponses];

export type itemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsUpdateItemError = itemsUpdateItemErrors[keyof itemsUpdateItemErrors];

export type itemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsUpdateItemResponse = itemsUpdateItemResponses[keyof itemsUpdateItemResponses];

export type developReadDevelopmentChatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/develop/chats';
};

export type developReadDevelopmentChatsResponses = {
    /**
     * Successful Response
     */
    200: DevelopmentChatsPublic;
};

export type developReadDevelopmentChatsResponse = developReadDevelopmentChatsResponses[keyof developReadDevelopmentChatsResponses];

export type developCreateDevelopmentChatData = {
    body: DevelopmentChatCreate;
    path?: never;
    query?: never;
    url: '/api/v1/develop/chats';
};

export type developCreateDevelopmentChatErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type developCreateDevelopmentChatError = developCreateDevelopmentChatErrors[keyof developCreateDevelopmentChatErrors];

export type developCreateDevelopmentChatResponses = {
    /**
     * Successful Response
     */
    200: DevelopmentChatPublic;
};

export type developCreateDevelopmentChatResponse = developCreateDevelopmentChatResponses[keyof developCreateDevelopmentChatResponses];

export type developDeleteDevelopmentChatData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: {
        /**
         * Confirm
         */
        confirm?: boolean;
    };
    url: '/api/v1/develop/chats/{chat_id}';
};

export type developDeleteDevelopmentChatErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type developDeleteDevelopmentChatError = developDeleteDevelopmentChatErrors[keyof developDeleteDevelopmentChatErrors];

export type developDeleteDevelopmentChatResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type developDeleteDevelopmentChatResponse = developDeleteDevelopmentChatResponses[keyof developDeleteDevelopmentChatResponses];

export type developReadDevelopmentChatData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/api/v1/develop/chats/{chat_id}';
};

export type developReadDevelopmentChatErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type developReadDevelopmentChatError = developReadDevelopmentChatErrors[keyof developReadDevelopmentChatErrors];

export type developReadDevelopmentChatResponses = {
    /**
     * Successful Response
     */
    200: DevelopmentChatPublic;
};

export type developReadDevelopmentChatResponse = developReadDevelopmentChatResponses[keyof developReadDevelopmentChatResponses];

export type developRenameDevelopmentChatData = {
    body: DevelopmentChatUpdate;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/api/v1/develop/chats/{chat_id}';
};

export type developRenameDevelopmentChatErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type developRenameDevelopmentChatError = developRenameDevelopmentChatErrors[keyof developRenameDevelopmentChatErrors];

export type developRenameDevelopmentChatResponses = {
    /**
     * Successful Response
     */
    200: DevelopmentChatPublic;
};

export type developRenameDevelopmentChatResponse = developRenameDevelopmentChatResponses[keyof developRenameDevelopmentChatResponses];

export type developReadDevelopmentWorkspaceData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/api/v1/develop/chats/{chat_id}/workspace';
};

export type developReadDevelopmentWorkspaceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type developReadDevelopmentWorkspaceError = developReadDevelopmentWorkspaceErrors[keyof developReadDevelopmentWorkspaceErrors];

export type developReadDevelopmentWorkspaceResponses = {
    /**
     * Successful Response
     */
    200: DevelopmentWorkspacePublic;
};

export type developReadDevelopmentWorkspaceResponse = developReadDevelopmentWorkspaceResponses[keyof developReadDevelopmentWorkspaceResponses];

export type developSetupDevelopmentWorkspaceData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/api/v1/develop/chats/{chat_id}/workspace/setup';
};

export type developSetupDevelopmentWorkspaceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type developSetupDevelopmentWorkspaceError = developSetupDevelopmentWorkspaceErrors[keyof developSetupDevelopmentWorkspaceErrors];

export type developSetupDevelopmentWorkspaceResponses = {
    /**
     * Successful Response
     */
    200: DevelopmentWorkspacePublic;
};

export type developSetupDevelopmentWorkspaceResponse = developSetupDevelopmentWorkspaceResponses[keyof developSetupDevelopmentWorkspaceResponses];

export type developUpdateDevelopmentPresenceData = {
    body: DevelopmentPresenceUpdate;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/api/v1/develop/chats/{chat_id}/presence';
};

export type developUpdateDevelopmentPresenceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type developUpdateDevelopmentPresenceError = developUpdateDevelopmentPresenceErrors[keyof developUpdateDevelopmentPresenceErrors];

export type developUpdateDevelopmentPresenceResponses = {
    /**
     * Successful Response
     */
    200: DevelopmentChatPublic;
};

export type developUpdateDevelopmentPresenceResponse = developUpdateDevelopmentPresenceResponses[keyof developUpdateDevelopmentPresenceResponses];

export type developReadDevelopmentMessagesData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: {
        /**
         * Before
         */
        before?: string | null;
        /**
         * After
         */
        after?: string | null;
    };
    url: '/api/v1/develop/chats/{chat_id}/messages';
};

export type developReadDevelopmentMessagesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type developReadDevelopmentMessagesError = developReadDevelopmentMessagesErrors[keyof developReadDevelopmentMessagesErrors];

export type developReadDevelopmentMessagesResponses = {
    /**
     * Successful Response
     */
    200: DevelopmentMessagesPublic;
};

export type developReadDevelopmentMessagesResponse = developReadDevelopmentMessagesResponses[keyof developReadDevelopmentMessagesResponses];

export type developProposeDevelopmentChatData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/api/v1/develop/chats/{chat_id}/messages/propose';
};

export type developProposeDevelopmentChatErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type developProposeDevelopmentChatError = developProposeDevelopmentChatErrors[keyof developProposeDevelopmentChatErrors];

export type developProposeDevelopmentChatResponses = {
    /**
     * Successful Response
     */
    200: DevelopmentMessagePublic;
};

export type developProposeDevelopmentChatResponse = developProposeDevelopmentChatResponses[keyof developProposeDevelopmentChatResponses];

export type developRejectDevelopmentProposalData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
        /**
         * Message Id
         */
        message_id: string;
    };
    query?: never;
    url: '/api/v1/develop/chats/{chat_id}/messages/{message_id}/reject';
};

export type developRejectDevelopmentProposalErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type developRejectDevelopmentProposalError = developRejectDevelopmentProposalErrors[keyof developRejectDevelopmentProposalErrors];

export type developRejectDevelopmentProposalResponses = {
    /**
     * Successful Response
     */
    200: DevelopmentMessagePublic;
};

export type developRejectDevelopmentProposalResponse = developRejectDevelopmentProposalResponses[keyof developRejectDevelopmentProposalResponses];

export type developApproveDevelopmentProposalData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
        /**
         * Message Id
         */
        message_id: string;
    };
    query?: never;
    url: '/api/v1/develop/chats/{chat_id}/messages/{message_id}/approve/stream';
};

export type developApproveDevelopmentProposalErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type developApproveDevelopmentProposalError = developApproveDevelopmentProposalErrors[keyof developApproveDevelopmentProposalErrors];

export type developApproveDevelopmentProposalResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type developStopCurrentTurnData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/api/v1/develop/chats/{chat_id}/turns/current';
};

export type developStopCurrentTurnErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type developStopCurrentTurnError = developStopCurrentTurnErrors[keyof developStopCurrentTurnErrors];

export type developStopCurrentTurnResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type developStopCurrentTurnResponse = developStopCurrentTurnResponses[keyof developStopCurrentTurnResponses];

export type developReadCurrentTurnData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/api/v1/develop/chats/{chat_id}/turns/current';
};

export type developReadCurrentTurnErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type developReadCurrentTurnError = developReadCurrentTurnErrors[keyof developReadCurrentTurnErrors];

export type developReadCurrentTurnResponses = {
    /**
     * Response Develop-Read Current Turn
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type developReadCurrentTurnResponse = developReadCurrentTurnResponses[keyof developReadCurrentTurnResponses];

export type developStreamCurrentTurnData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/api/v1/develop/chats/{chat_id}/turns/current/stream';
};

export type developStreamCurrentTurnErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type developStreamCurrentTurnError = developStreamCurrentTurnErrors[keyof developStreamCurrentTurnErrors];

export type developStreamCurrentTurnResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type developDetachCurrentTurnData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/api/v1/develop/chats/{chat_id}/turns/current/attach';
};

export type developDetachCurrentTurnErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type developDetachCurrentTurnError = developDetachCurrentTurnErrors[keyof developDetachCurrentTurnErrors];

export type developDetachCurrentTurnResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type developDetachCurrentTurnResponse = developDetachCurrentTurnResponses[keyof developDetachCurrentTurnResponses];

export type developAttachCurrentTurnData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/api/v1/develop/chats/{chat_id}/turns/current/attach';
};

export type developAttachCurrentTurnErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type developAttachCurrentTurnError = developAttachCurrentTurnErrors[keyof developAttachCurrentTurnErrors];

export type developAttachCurrentTurnResponses = {
    /**
     * Response Develop-Attach Current Turn
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type developAttachCurrentTurnResponse = developAttachCurrentTurnResponses[keyof developAttachCurrentTurnResponses];

export type developStreamDevelopmentChatExplorationData = {
    body: DevelopmentMessageCreate;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/api/v1/develop/chats/{chat_id}/messages/explore/stream';
};

export type developStreamDevelopmentChatExplorationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type developStreamDevelopmentChatExplorationError = developStreamDevelopmentChatExplorationErrors[keyof developStreamDevelopmentChatExplorationErrors];

export type developStreamDevelopmentChatExplorationResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type developExploreDevelopmentChatData = {
    body: DevelopmentMessageCreate;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/api/v1/develop/chats/{chat_id}/messages/explore';
};

export type developExploreDevelopmentChatErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type developExploreDevelopmentChatError = developExploreDevelopmentChatErrors[keyof developExploreDevelopmentChatErrors];

export type developExploreDevelopmentChatResponses = {
    /**
     * Successful Response
     */
    200: DevelopmentMessagePublic;
};

export type developExploreDevelopmentChatResponse = developExploreDevelopmentChatResponses[keyof developExploreDevelopmentChatResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
