services:
  db:
    ports: []

  backend:
    ports:
      - "127.0.0.1:${ACCEPTANCE_PORT:?Variable not set}:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/utils/health-check/"]
    environment:
      FASTAPI_ENV: development
      FRONTEND_HOST: "http://127.0.0.1:${ACCEPTANCE_PORT:?Variable not set}"
      SMTP_PORT: "1025"
      SMTP_TLS: "false"